FROM python:3.12-slim

WORKDIR /app

# Copiar apenas o requirements.txt primeiro para aproveitar o cache do Docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código da aplicação
COPY src/ ./src/

# Adicionar o diretório src ao PYTHONPATH
ENV PYTHONPATH=/app/src

EXPOSE 80

# Comando para executar a aplicação
CMD ["gunicorn", "--bind", "0.0.0.0:80", "src.app:app"]
